import Head from 'next/head';
import Header from '../components/Reuseables/Header';
import Drawer from '../components/Drawer/Drawer';
import BackDrop from '../components/Drawer/BackDrop';
import {useState} from 'react';
import Right from '../components/Checkout/right'
import Left from '../components/Checkout/left';

const Checkout = () => {

	const [drawer, setDrawer] = useState(false);
	const showDrawer = () => setDrawer(!drawer);

	let backdrop;

	if (drawer) {
		backdrop = <BackDrop showDrawer={showDrawer} />;
	}

	return (
		<div className='bg-gray-100'>
			<Head>
				<title>Checkout</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header showDrawer={showDrawer} />
			<Drawer drawer={drawer} showDrawer={showDrawer} />
			{backdrop}
			
			<div className='lg:pt-[130px] lg:px-[60px] lg:pb-[60px] pt:pt-[60px] w-full relative bg-gray-100'>
				<div className='lg:w-[970px] lg:ml-auto lg:mr-auto flex w-full'>
                 <Right />
				 <Left />
                </div>
			</div>
		</div>
	);
};

export default Checkout;
