import Head from 'next/head'
import Header from '../components/Home/Header'
import Home from '../components/Home/Body'
import Topfiltered from '../components/Side/Topfiltered'
import { useState } from 'react';
import BackDrop from '../components/Drawer/BackDrop';
import FilterDrawer from '../components/Side/FilterDrawer';
import Drawer from '../components/Drawer/Drawer'

export default function Index() {

  const [drawer, setDrawer] = useState(false);

	const showDrawer = () => setDrawer(!drawer);

	let backdrop

	if (drawer){
		backdrop = <BackDrop showDrawer={showDrawer} />
	}
  return (
    <div>
      <Head>
        <title>Ajao Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header showDrawer={showDrawer}/>
			<Drawer drawer={drawer} showDrawer={showDrawer}/>
			{backdrop}

     
      <div className='bg-gray-100'>
      <Home/>
      </div>
    </div>
  )
}
