import Head from 'next/head'
import Header from '../components/Home/Header'
import Home from '../components/Home/Body'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Ajao Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className='bg-gray-100'>
      <Home/>
      </div>
    </div>
  )
}
