import LoginForm from '../components/Auth/LoginForm';
import SignUp from '../components/Auth/SignUp';
import { useState } from 'react';
import { loginContext } from '../components/Auth/loginContext';
import Head from 'next/head';

const login = () => {
	const [active, setActive] = useState('signin');

	const SwitchToSignUp = () => {
		setActive('signup');
	};
	const SwitchToSignIn = () => {
		setActive('signin');
	};

	const ContextV = {
		SwitchToSignUp,
		SwitchToSignIn,
	};
	return (
		<>
			<Head>
				<title>Login</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<loginContext.Provider value={ContextV}>
				<div className='box-border flex items-center justify-center w-full h-full'>
					<div className='p-8 bg-white border rounded shadow lg:w-[458px] lg:top-[100px] top-[30px] h-auto absolute lg:left-[35%]'>
						<div className='box-border w-full h-full'>
							<div className='text-center bg-white'>
								<div className='pt-[2px] px-[30px]'>
									{active === 'signin' && (
										<div>
											<h3 className='mb-2 text-2xl font-semibold text-secondary-main'>
												Welcome Back
											</h3>
											<span className='block text-base font-normal text-gray-400 mb-7'>
												Login with your email & password
											</span>
										</div>
									)}
									{active === 'signup' && (
										<div>
											<h3 className='mb-2 text-2xl font-semibold text-secondary-main'>
												Sign Up
											</h3>
											<span className='block text-base font-normal text-gray-400 mb-7'>
												By signing up, you agree to
												Pickbazar's
											</span>
										</div>
									)}
									{active === 'signin' && <LoginForm />}
									{active === 'signup' && <SignUp />}
								</div>
							</div>
						</div>
					</div>
				</div>
			</loginContext.Provider>
		</>
	);
};

export default login;
