import LoginForm from '../components/Auth/LoginForm';
import SignUp from '../components/Auth/SignUp';
import {useState} from 'react';
import {loginContext} from '../components/Auth/loginContext';
import Head from 'next/head';

const login = () => {
	const [active, setActive] = useState('signin');

	const SwitchToSignUp = () => {
		setActive('signup');
	};
	const SwitchToSignIn = () => {
		setActive('signin');
	};

	const ContextV = {
		SwitchToSignUp,
		SwitchToSignIn,
	};
	return (
		<>
			<Head>
				<title>Login</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<loginContext.Provider value={ContextV}>
				<div className='w-full h-full flex box-border'>
					<div className='wrapper rounded border bg-white  shadow p-8'>
						<div className='w-full h-full box-border'>
							<div className='text-center bg-white'>
								<div className='loginContent'>
									{active === 'signin' && (
										<div>
											<h3 className='mb-2 text-2xl font-semibold text-green-600'>
												Welcome Back
											</h3>
											<span className='mb-7 text-base font-normal block text-gray-400'>
												Login with your email & password
											</span>
										</div>
									)}
									{active === 'signup' && (
										<div>
											<h3 className='mb-2 text-2xl font-semibold text-green-600'>
												Sign Up
											</h3>
											<span className='mb-7 text-base font-normal block text-gray-400'>
												By signing up, you agree to
												Pickbazar's
											</span>
										</div>
									)}
									{active === 'signin' && <LoginForm />}
									{active === 'signup' && <SignUp />}
								</div>
							</div>
						</div>
					</div>
				</div>
			</loginContext.Provider>
		</>
	);
};

export default login;
