import Head from 'next/head';
import Header from '../components/Reuseables/Header';
import SideBar from '../components/Reuseables/Sidebar';
import Orderdetail from '../components/order/Orderdetail';
import Order from '../components/order/Order'
import { useState } from 'react';
const order = () => {
	const [currentStep, setCurrentStep] = useState(1);

	return (
		<div>
			<Head>
				<title>Order</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className='w-full h-auto min-h-screen flex flex-wrap bg-white SidebarBody '>
				<SideBar />
				<div className='lg:w-calc flex flex-start w-full px-[20px]'>
					<div className='hidden lg:flex'>
						<Orderdetail currentStep={currentStep} setCurrentStep={setCurrentStep}/>
						<Order currentStep={currentStep} setCurrentStep={setCurrentStep}/>
					</div>
				</div>
			</div>
		</div>
	);
};

export default order;
