import Head from 'next/head';
import Header from '../components/Reuseables/Header'
import SideBar from '../components/Profile/Sidebar'
import ProfileForm from '../components/Profile/ProfileForm'

const profile = () => {
	return (
		<div className=''>
			<Head>
				<title>Profile</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className='w-full h-auto min-h-screen flex flex-wrap bg-white lg lg:mh lg:xm lg:pb-8'>
				<SideBar />
				<ProfileForm />
			</div>
		</div>
	);
};

export default profile;
